module_id: G
name: 模块G
type: 均衡型
beds: 4
cost: 3384
priority: 3
dimensions:
  length_mm: 2800
  width_mm: 4100
bed_orientation:
  head_direction: north
  head_position_mm: 4100
road_areas: []
beds_layout:
- bed_id: 1
  head_direction: north
  head_position_mm: 4100
  polygon:
  - - 0
    - 2200
  - - 900
    - 2200
  - - 900
    - 4099
  - - 0
    - 4100
- bed_id: 2
  head_direction: west
  head_position_mm: 4100
  polygon:
  - - 900
    - 3200
  - - 2800
    - 3200
  - - 2800
    - 4100
  - - 900
    - 4100
- bed_id: 3
  head_direction: east
  head_position_mm: 900
  polygon:
  - - 0
    - 0
  - - 1900
    - 0
  - - 1900
    - 900
  - - 0
    - 900
- bed_id: 4
  head_direction: south
  head_position_mm: 4100
  polygon:
  - - 1900
    - 0
  - - 2800
    - 0
  - - 2800
    - 1900
  - - 1900
    - 1900
visual:
  single_texture: moduleG_single.png
  color: '#00008B'
